// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNWWWWMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNXXXXNNNNNWWWWMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXKKKKKXXNNWWMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXK0000KXNNWMMMMMMMMMMMMMMMMMMMMMMMMM
// MWXKKKKKKKKKKK00KKKXWMMMMMMMNK0000000KKKK00000KKXWMMMMMMMMMMWNNMMMMMMMMMMMMMMMMWNXKK00KKKKKKK00KKKXNWWMMMMMMNKK0KKKKKKKKKKKKKKKKKXWMMMMWK000000XWMMMMMMMMMMMWWXK0OOOOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// 0l;,,;;;;;;;;;;;;;;:oKWMMMMWk;,,,,;;;;;;;;;;;,,,:l0WMMMMMMMXd:oKWMMMMMMMMMMMMMNx:;,,,;;;;;;;;;;;;;:cokNMMMMWO:,,,,,,,,,,,,,,,,,,,oNMMMMNOl;,,,,;oOXWMMMMWNXK0OkkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// o'''oO000000000000000XWMMMMWx,'',d00000000000d;'''dNMMMMMMWO;'':kNMMMMMMMMMMMM0:'''ckOOOOOOOO00OOO0OOKWMMMMMXOkkkkkkkkkkkkkkkkOOOKWMMMMMMN0d:,''.,cONWXK0kkkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// o'',o0KKKKKKKKKKKKKXNWMMMMMWx,'';kWWWWWWWWWWW0:'''oNMMMMMMMWO:'',oKWMMMMMMMMMMO;.''dWMMMMMMMMMMMMMMMMMMMMMMMKxdddddddddddxONMMMMMMMMMMMMMMMWNOoclxkO0OkkkO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// k;'',,,,,,,,,,,,,,;;cxNMMMMWx,''':lllllllllll:,'',xWMMMMMMMMWKl,.':ONMMMMMMMMMO;'''dWMMMMMMMMMMMMMMMMMMMMMMWk,''';ccccccccxNMMMMMMMMMMMMMMMMMMWXK0OkkkO0OOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// WKOkkxxxxxxxxxxxxo;'';OMMMMWx,'''cooooooooooooodx0NMWKkxxxxxxxo,''',dXWMMMMMMMO;'''dWMMMMMMMMMMMMMMMMMMMMMMMk,'',xNWWWWWWWWMMMMMMMMMMMMMMMMMNX0Okkkk00kl;,:d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// WWWWWWWWWWWWWWWWW0c'';OMMMMWx,'';OWMMMMMMMMMMMMMMMMW0o:::::::::;;,'.'cOWMMMMMMO;'''dNWWWWWWWWWWWWWWWWWMMMMMMk,'',xWMMMMMMMMMMMMMMMMMMMMMMWNKOkkkkOKNWXx:'''',cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// ollllllllllllllll:,''c0MMMMWx,'.;OMMMMMMMMMMMMMMMMMWNXXXXXXXXXXXX0o,'';dXWMMMMKc''';cllllllllllllllllkNMMMMWk,''':ooooooooooooood0WMMMMWX0kkkkkOKNWMMMWXkl;'''';lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// d:,''''''''''''''',;cOWMMMMWx,'':OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,'',dXMMMMWOc;,'''''''''''''',;ld0WMMMMMk;'''''''''''''''''',dWMMMMXOkkkkk0NMMMMMMMMMNOc,'''',lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

package main

import (
	"fmt"
	"github.com/n7down/Displays/internal/spacexapi"
	log "github.com/sirupsen/logrus"
	"time"
)

// TODO: build
// 1. every 1 min - get the current time in utc
// 2. query the spacex api to get the next launch in utc:
// - curl --location --request GET "https://api.spacexdata.com/v3/launches/next" | jq '.launch_date_utc'
// 3. translate the difference of the year, month, day, hour, minute, second and millisecond? into rgb
// - where each rgb value is between 0 and 255
// - for each new row get the rgb value below it and divide it by 2
// - so if there are 4 rows then the first row is the original rgb the 2nd row is the 1st row divided by 2
// - then the 3rd row is the 2nd row divided by 2 and so on
// 4. render to the blinky tape

const (
	spaceXClockVersion = "1.0.0"
)

func main() {

	nextLaunch, err := spacexapi.GetNextLaunch()
	if err != nil {
		log.Error(err)
	}

	currentDateTime := time.Now().UTC()
	nextLaunchDateUtc := nextLaunch.LaunchDateUtc

	fmt.Println("____ ___  ____ ____ ____ _  _")
	fmt.Println("[__  |__] |__| |    |___  \\/")
	fmt.Printf("___] |    |  | |___ |___ _/\\_   v%s\n", spaceXClockVersion)
	fmt.Println()
	fmt.Println("NEXT LAUNCH ==================================================")
	fmt.Printf(" Date UTC: %s\n", nextLaunchDateUtc)
	fmt.Printf(" Current UTC: %s\n", currentDateTime)
	fmt.Printf(" Time: %s\n", time.Now())
	fmt.Printf(" Elapsed: %s\n", time.Since(nextLaunchDateUtc))
}
